import { Injectable } from '@nestjs/common';
import { User } from '@carecore/shared';
import { ROLES } from '../constants/roles';

/**
 * Patient Context Service
 *
 * Centralizes the logic for determining patient filtering criteria based on user context.
 * This service unifies the different approaches used across the codebase:
 *
 * - For users with 'patient' role: Uses keycloakUserId (direct database link)
 * - For SMART on FHIR context: Uses patientId from token (interoperability)
 * - For admins: No filtering (can see all)
 * - For practitioners: Filter by active status
 *
 * @description
 * This service addresses the confusion between three different patient identifiers:
 *
 * 1. **id** (UUID): Database primary key, auto-generated by TypeORM
 *    - Internal database identifier
 *    - Example: "550e8400-e29b-41d4-a716-446655440000"
 *
 * 2. **patientId** (string): FHIR resource ID, extracted from fhirResource.id
 *    - Public identifier used in FHIR references (e.g., "Patient/patient-123")
 *    - Generated when creating a patient resource
 *    - Used for SMART on FHIR patient context filtering
 *
 * 3. **keycloakUserId** (string | null): Keycloak user ID that owns the patient record
 *    - Links Patient resource to Keycloak user account
 *    - Used for authorization: patients can only access their own records
 *    - Nullable to support patients created before user linking
 *    - Used for role-based filtering when user has 'patient' role
 *
 * @example
 * ```typescript
 * const filterCriteria = patientContextService.getPatientFilterCriteria(user);
 * if (filterCriteria.type === 'keycloakUserId') {
 *   queryBuilder.andWhere('patient.keycloakUserId = :keycloakUserId', {
 *     keycloakUserId: filterCriteria.value
 *   });
 * } else if (filterCriteria.type === 'patientId') {
 *   queryBuilder.andWhere('patient.patientId = :patientId', {
 *     patientId: filterCriteria.value
 *   });
 * }
 * ```
 */
@Injectable()
export class PatientContextService {
  /**
   * Extracts patient ID from SMART on FHIR context
   * Supports both "Patient/123" format and plain "123" format
   */
  private extractPatientIdFromContext(patientContext?: string): string | undefined {
    if (!patientContext) {
      return undefined;
    }

    // Remove "Patient/" prefix if present
    return patientContext.replace(/^Patient\//, '');
  }

  /**
   * Gets the patient filter criteria based on user context
   *
   * Priority order:
   * 1. SMART on FHIR patient context (user.patient or user.fhirUser) - highest priority
   * 2. User role 'patient' - uses keycloakUserId
   * 3. Admin - no filter (returns null)
   * 4. Practitioner - filter by active status (returns special type)
   *
   * @param user - Current authenticated user
   * @returns Filter criteria or null if no filtering needed
   */
  getPatientFilterCriteria(
    user?: User,
  ):
    | { type: 'keycloakUserId'; value: string }
    | { type: 'patientId'; value: string }
    | { type: 'active'; value: boolean }
    | null {
    if (!user) {
      return null;
    }

    // Admin can see all patients (no filter)
    if (user.roles?.includes(ROLES.ADMIN)) {
      return null;
    }

    // Priority 1: SMART on FHIR patient context (for interoperability)
    // This takes precedence because it's more specific and comes from the token
    const tokenPatientId = this.extractPatientIdFromContext(user.patient || user.fhirUser);
    if (tokenPatientId) {
      return { type: 'patientId', value: tokenPatientId };
    }

    // Priority 2: User with 'patient' role (direct database link)
    // Uses keycloakUserId because it's the direct link between user and patient record
    if (user.roles?.includes(ROLES.PATIENT)) {
      return { type: 'keycloakUserId', value: user.id };
    }

    // Priority 3: Practitioner can see all active patients
    if (user.roles?.includes(ROLES.PRACTITIONER)) {
      return { type: 'active', value: true };
    }

    // Other roles need explicit consent (no access by default)
    return null;
  }

  /**
   * Gets the patient ID for FHIR references (Patient/{id})
   * Used when filtering other resources by patient (e.g., Encounter, Consent)
   *
   * @param user - Current authenticated user
   * @returns Patient ID in FHIR format (e.g., "Patient/123") or undefined
   */
  getPatientReference(user?: User): string | undefined {
    const criteria = this.getPatientFilterCriteria(user);

    if (!criteria) {
      return undefined;
    }

    if (criteria.type === 'patientId') {
      return `Patient/${criteria.value}`;
    }

    if (criteria.type === 'keycloakUserId') {
      // For keycloakUserId, we need to look up the patientId
      // This is handled by the calling service
      return undefined;
    }

    return undefined;
  }

  /**
   * Checks if user should bypass patient filtering (admin)
   */
  shouldBypassFiltering(user?: User): boolean {
    if (!user) {
      return false;
    }

    return user.roles?.includes(ROLES.ADMIN) ?? false;
  }

  /**
   * Gets the keycloakUserId for direct database queries
   * Only returns a value if user has 'patient' role and no SMART context
   *
   * @param user - Current authenticated user
   * @returns Keycloak user ID or undefined
   */
  getKeycloakUserId(user?: User): string | undefined {
    const criteria = this.getPatientFilterCriteria(user);

    if (criteria?.type === 'keycloakUserId') {
      return criteria.value;
    }

    return undefined;
  }

  /**
   * Gets the patientId for FHIR resource queries
   * Only returns a value if user has SMART on FHIR patient context
   *
   * @param user - Current authenticated user
   * @returns Patient ID or undefined
   */
  getPatientId(user?: User): string | undefined {
    const criteria = this.getPatientFilterCriteria(user);

    if (criteria?.type === 'patientId') {
      return criteria.value;
    }

    return undefined;
  }
}
