import { IsString, IsNotEmpty, IsOptional, IsIn, Matches } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * DTO for SMART on FHIR Authorization endpoint parameters
 * Based on OAuth2 Authorization Code Flow and SMART on FHIR specifications
 *
 * @example
 * {
 *   "client_id": "app-123",
 *   "response_type": "code",
 *   "redirect_uri": "https://app.com/callback",
 *   "scope": "patient:read patient:write",
 *   "state": "abc123",
 *   "aud": "https://fhir.example.com"
 * }
 */
export class SmartFhirAuthDto {
  @ApiProperty({
    description: 'Client ID of the SMART on FHIR application',
    example: 'app-123',
  })
  @IsString()
  @IsNotEmpty()
  client_id: string;

  @ApiProperty({
    description: 'Response type - must be "code" for Authorization Code flow',
    example: 'code',
    enum: ['code'],
  })
  @IsString()
  @IsNotEmpty()
  @IsIn(['code'], { message: 'response_type must be "code" for Authorization Code flow' })
  response_type: string;

  @ApiProperty({
    description: 'Redirect URI where the authorization code will be sent',
    example: 'https://app.com/callback',
  })
  @IsString()
  @IsNotEmpty()
  redirect_uri: string;

  @ApiProperty({
    description: 'Space-separated list of scopes requested (e.g., "patient:read patient:write")',
    example: 'patient:read patient:write',
  })
  @IsString()
  @IsNotEmpty()
  scope: string;

  @ApiPropertyOptional({
    description:
      'CSRF protection token - should be generated by the client and validated on callback',
    example: 'abc123xyz',
  })
  @IsOptional()
  @IsString()
  state?: string;

  @ApiPropertyOptional({
    description: 'Audience - URL of the FHIR server (SMART on FHIR extension)',
    example: 'https://fhir.example.com',
  })
  @IsOptional()
  @IsString()
  @Matches(/^https?:\/\/.+/, {
    message: 'aud must be a valid URL',
  })
  aud?: string;
}
